name: Playwright run tests with Allure report
on:
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      E2E_FOLDER: "tests"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --force

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force

      - name: Run Playwright tests
        run: npx playwright test ${{ env.E2E_FOLDER }} --reporter=line,allure-playwright

      - name: Upload Playwright Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

  allure-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Install Allure
        run: npm install -g allure-commandline --force

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report

      # - name: Display Allure Report URL
        # run: echo "Allure report available at: https://<username>.github.io/<repository-name>/"
